name: Add issues to project
on:
  issues:
    types: [opened, labeled, reopened] # Triggers when an issue is opened, labeled, or reopened

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/add-to-project@main
      with:
        # The URL of the project board (e.g., https://github.com/orgs/<orgName>/projects/<projectNumber>)
        project-url: https://github.com/users/bryanjonker-illinois/projects/1
        github-token: ${{ secrets.SAMPLE_PROJECT_OLD }}
